on: [push]

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.75.0
          target: wasm32-unknown-unknown
          components: clippy
      - run: cargo install wasm-pack --version 0.9.1
      - uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
      - run: npm install
      - run: npm test
      - run: npm run build
